version: "3"

services:
  jenkins:
    image: cicd-jenkins:latest
    # image: jenkins/jenkins:lts
    container_name: cicd-jenkins
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - cicd-net
    volumes:
      - /data/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    # image: cicd-sonarqube:latest
    image: sonarqube:lts
    container_name: cicd-sonarqube
    ports:
      - 9000:9000
    networks:
      - cicd-net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - /data/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - /data/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /data/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /data/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    container_name: cicd-postgres
    ports:
      - 5432:5432
    networks:
      - cicd-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /data/postgres/postgresql:/var/lib/postgresql
      - /data/postgres/postgresql_data:/var/lib/postgresql/data

networks:
  cicd-net:
